### ISSUE TITLE
[2.0.0016] Warning message is not shown when incorrect qualifier is input.

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#606] opened 2014-01-18 09:16 UTC
Preq: 1. Install VS2013 plugin from Bundle 193[2.0.0016] on Win8.1
         2. Device/Simulator correct information in Blackberry VS Plugin Settings
1. Debug > Attach To Process
2. Attach to process dialog is opened
   ![image](https://f.cloud.github.com/assets/5992406/1946716/67446242-801d-11e3-89b4-bd87c1af93d4.png)
3. Select Transport Blackberry
4. Input Incorrect Qualifier Device IP address
   ![image](https://f.cloud.github.com/assets/5992406/1946728/4c8743c4-801e-11e3-9c1d-2090a918ed25.png)

Actual Result:
It didn't prompt any error message.

Expected Result:
It should warn about incorrect blackberry device qualifier after made changes IP address.

**Comment by srinivas4912** [comment] 2014-01-18 09:33
Observed intermittently, when clicked on Refresh button "Device/Simulator not connected or not configured properly" dialog opened.

**Comment by guarnold** [comment] 2014-01-20 17:41
The user can only select between the two options that were set using BlackBerry -> Settings menu, one for simulator and another for device, at most.

Because the Qualifier text field is editable, the current behavior when the user type in that field is to chose between the two available options. It normally picks the one that looks similar to the typed one. If none of them is similar, it chooses the first available option (normally the device one). That's why you don't see any error message.

Using your example, the default device one is 169.254.0.1. Then you typed 169.254.0.12. Instead of verifying the new IP that you typed, the plug-in will use the available one that looks similar to the one you typed, that is exactly the "device: 169.254.0.1". If you were able to get the list of the processes, check the qualifier and you will see that it is not the one you typed; if you are not able to get the list of processes, it means that the IP or the password that you entered in the BlackBerry -> Settings menu is wrong (you will see an error message in this case).

This is the expected behavior because, if the user can type whatever IP he wants, he will probably have to wait some time till it gets a timeout error.

Workaround in case the user wants to use a different IP: Go to BlackBerry -> Settings menu and update the field you want (device or simulator).

**Comment by guarnold** [comment] 2014-01-23 15:24
I would recommend to close this issue as soon as we document it.

**Closed as completed** 2014-01-24 06:36 UTC
Labels: Issue, P3, Known Issue (Internal Use Only), Recommend Closure, VS 2013
