### ISSUE TITLE
[2.0.0018] It's opening empty window when click on "OK" button on "Signing keys not registered" window

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#620] opened 2014-01-25 13:53 UTC
Preq: 1. Install VS2013 plug-in from Bundle 195[2.0.0018] on Win7 64bit and using Naples R085 with 10.2.1.1925 build OS

Steps to reproduce:
1. Signing keys not registered. Make sure the "Research In Motion" folder is empty.
![image](https://f.cloud.github.com/assets/5992406/2001728/3d82492e-85c7-11e3-9917-5710e1d7abf2.png)
2. Open bar-descriptor.xml file from one of the project.
3. Click on "Set from Debug Token" button".
4. It prompts to "Signing keys not registered" window.
![image](https://f.cloud.github.com/assets/5992406/2001737/882afc0a-85c7-11e3-8bed-12acd03f7551.png)
5. Click on "OK".

Actual Result: It prompts to "Empty" window
![image](https://f.cloud.github.com/assets/5992406/2001738/aa705d32-85c7-11e3-80b3-2cf5d67ea0a6.png)

Note: The same issue reproduced using VS2013 plug-in from bundle 195[2.0.0018] on Win8.1 also

**Comment by guarnold** [comment] 2014-01-25 19:48
By mistake I clicked in close button.

**Comment by hkopparru** [comment] 2015-01-16 12:32
in 3.0 plugin the issue is not reproduced, where if you click on "Set from Debug Token button" button then it will open a window for selecting .bar file, where you can select the bar file if you have.

closing this issue now.

**Closed as completed by hkopparru** 2015-01-16 12:32 UTC
Labels: Issue, P3, VS 2013
