### ISSUE TITLE
[1.01.0032] runtime prompt appears when launching projects on a 10.1 and 10.0 device

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#420] opened 2013-09-06 18:10 UTC
1. Launch project for debugging

current behaviour:
prompt to update runtime appears user has to download in order to debug.

**Comment by dbrgss** [comment] 2013-09-09 17:17
I cannot reproduce this behavior.   Ken in his email said he couldn't reproduce it either on his machine.   Zad, Gustavo have you been able to get this to happen??   I will need more information from Ken's team members and what they did to get this behavior before I can continue.

**Comment by zadmarbella** [comment] 2013-09-09 17:35
@dbrgss The OS on the device is 10.0.10.756 that I just tried it on. It is not listed in eclipsec.exe --list-all.

**Comment by dbrgss** [comment] 2013-09-09 17:38
Ahh Okay..   That makes sense

Now my next question is.. . Is the 10.0.10.756 an officially released OS for the device or is it an internal version that WE can get because we work for BlackBerry... As far as I know the Eclipsec --list-all command should list ALL the officially supported API levels..  if it's not there I will have to let Doug know.

**Comment by zadmarbella** [comment] 2013-09-09 17:41
it's probably not supported.

**Comment by allee** [comment] 2013-09-20 15:10
closing as it is an internal only issue that is not supported.

**Closed as completed by allee** 2013-09-20 15:10 UTC
Labels: Issue, P2, Not an Issue
