### ISSUE TITLE
[2.0.0022] Title of the same error message is shown differently at different instances.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#652] opened 2014-02-20 12:45 UTC
Preq: 
Win OS: Win 7 64 bvit / Win 8.1 64 bit
API Level : 10.2.0.1155
Device OS: 10.2.0.1809
VS version : VS2012 / VS2013

Steps to Reprouduce:
1. Have a back-up of a set of signing keys (A).
2. Register with another set of signing keys (B).
3. Open Signing window.
4. Observe that signing keys are registered (Register button is disabled, Un-register button is disabled).
5. Click "Restore" button.
6. Select the back-up file of A signing keys (.zip file)
7. Observe that the signing keys are restored (Register button is disabled, Un-register button is disabled).
8. Open Blackberry->Debug token dialog.
9. Connect a device having the debug token and press "Renew"

Actual Result: Following error message is shown.

![1](https://f.cloud.github.com/assets/5992422/2218299/3382c2f4-9a2c-11e3-9c9c-1674277a0210.png)
1. Click "Retry"
2. Enter wrong BBID token password (which is not correct "A" signing key password).

Following error message is shown.

![2](https://f.cloud.github.com/assets/5992422/2218317/6eb5d00a-9a2c-11e3-8f3f-1c500177d784.png)

Observe that the title of the same error message is different in these 2 instances.

**Comment by hkopparru** [comment] 2015-01-16 11:18
retry and renew options are removed from the 3.0 plugin. so the problem is not reproduced here and here we can successfully upload the debug tokens from back up or restore packages

so closing this issue.

**Closed as completed by hkopparru** 2015-01-16 11:18 UTC
Labels: Issue, P3, VS 2012, VS 2013
