### ISSUE TITLE
[2.0.0016] Runtime Installation is prompting continuously 

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#602] opened 2014-01-17 11:38 UTC
Steps to reproduce:
1. Install VS2012 on Win 7 32bit and VSNDK bundle 193[2.0.0016].
2.Debug the project.
3. Runtime installation dialog is opened as follows.
![runtime](https://f.cloud.github.com/assets/5992422/1939852/82a56944-7f6b-11e3-8c59-fc54365d6063.png)
4.Install runtimes.
5.After completion of installing runtimes click close.

Actual result: Application is not continued to install on to the device. Following dialog is shown.
![debug](https://f.cloud.github.com/assets/5992422/1939859/bbfc2a34-7f6b-11e3-9e39-987e590f4045.png)

Tried to debug the project for multiple times. Runtime installation dialog is opening and above process is repeating.

**Comment by guarnold** [comment] 2014-01-17 13:54
Please, look at the Output Window to see if there are errors in the build/deploy process and paste them here.
This message happens when the VS debugger cannot attach to a running process. It might be caused by many reasons and some of them are described in the output window.

Another question, was the application deployed and launched in the device/simulator?

**Comment by pvallabhaneni** [comment] 2014-01-17 15:17
Application is deployed into the device and there are no errors found in the output window.Application is not running automatically.Only a black screen is visible on the device. If the black screen is closed on the device and application is started again on the device, it is running without any problem.

Following is found in output window.

1>------ Deploy started: Project: FallingBlocks_MltThrd_001, Configuration: Debug BlackBerry ------
1>  Info: Sending request: INSTALL_AND_LAUNCH
1>  Info: Action: Install and Launch
1>  Info: Debug native: on
1>  Info: File size: 18131
1>  Info: Installing com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa...
1>  Info: Processing 18131 bytes
1>  Info: Progress 100%...
1>  actual_dname::com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  actual_id::testDev_MltThrd_001452978aa
1>  actual_version::1.0.0.1
1>  result::success
1>  Info: Launching com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa...
1>  result::15741138
1>  Info: done
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by guarnold** [comment] 2014-01-17 18:40
I could reproduce that issue once, but because I know that I always have to check the output window for errors, I found out that I had to rebuild the app because the bar-descriptor file was changed. After rebuilding, it worked as expected. However, the current error message is not so clear, suggesting the user only to check for the running app in the device, instead of suggesting him to look at the output window for errors.

About the Runtime installation dialog, it should be presented only when the runtime is not installed. After installing it, this message should not appear anymore, unless you are using an OS that needs an API level/runtime that is not available outside yet. Or if your bbndk_vs folder is corrupted. 

So, please follow the following instructions to try to solve this issue:
1 - have a look at the output window to identify the error. If you know how to fix it, do it. If not, include the error message in the comments;
2 - If you are seeing the runtime installation dialog after having installed it, have a look if the respective runtime folder exists in the c:\bbndk_vs folder. If it does not exist after installing the runtime, the folder is probably corrupted.
  2.1 - you could try to reproduce this runtime issue in another environment.
  2.1 - if bbndk_vs folder is corrupted, close VS, delete the entire bbndk_vs folder, as well as the c:\qconfig one and open VS again. You will have to re-install the API levels and runtimes and this issue should not be reproducible anymore.

**Comment by guarnold** [comment] 2014-01-17 18:55
I received your message just a few minutes ago, after publishing my comments 10 minutes ago... 

That black screen in the device means that the application was deployed and launched in the device correctly, and it is waiting for the debugger to attach to it.

Could you try running a different app, like the single thread falling blocks? I thing that this issue could be related to the multi thread version of falling blocks. If other apps runs normally, I will know where to investigate: the multi threads feature.

**Comment by pvallabhaneni** [comment] 2014-01-18 06:45
I tried on a fresh machine. After installation runtime is completed, runtime folder is not found in vsndk_vs folder.

![bug](https://f.cloud.github.com/assets/5992422/1946510/be3e3846-800b-11e3-8ffe-2b3a6584ed06.PNG)

And so runtime installation dialog is shown every time and then after closing it "Failed to launch debugger" is shown.

**Comment by guarnold** [comment] 2014-01-20 23:18
I still cannot reproduce this issue in VS 2013 and 2012 (64 and 32 bits).

Please, include the used OS version from the device (Settings -> About -> OS -> OS Version). Depending on the OS Version, the runtime dialog might always appear without installing the runtime successfully.

Please, also include the selected API Level from the plugin: BlackBerry -> Settings -> BlackBerry API Levels), There is an issue when using API levels 10.0 and 10.1 (the debugger cannot attach to the running process and then you see that error message.).

Depending on the answers, this issue could be a duplicate of another ones.

**Comment by pvallabhaneni** [comment] 2014-01-21 05:31
OS version used on the device is 10.1.0.4828. API level downloaded is 10.2.0.1155 from GetMore as per one test case.

**Comment by guarnold** [comment] 2014-01-21 14:45
The debugger is not being attached to the running process because of the issue #609 (this part is a duplicate of 609). It is being fixed and will be available in the next build.

The issue related to the runtime: I am going to verify the behavior when the OS version is older than the selected API Level. However, the behavior related to API levels/runtime changed for the last build. Before, the API Level to be used was based on the device OS, but now it is based on the user selection. That means that the user has to select the correct API level from the list in BlackBerry->Settings and it cannot be newer than the device OS version.

In this case, you have to select the API Level 10.1 as this is the one associated to the device OS. You can also select 10.0, because the device OS 10.1 is compatible with the API level 10.0

**Comment by guarnold** [comment] 2014-01-24 00:01
About the first issue, the debugger is not being attached to the running process: Duplicate of #609

About the runtime issue: If the app was build using an API level that is newer than the OS version of the attached device/simulator, an error message is presented to the user stating that he cannot deploy and debug that app. If he wants to use that device/simulator, he have two options: 1 - update the OS version; 2 - select an API level that is compatible with the OS version, rebuild the app and hit play button again.  

The runtime window will be presented only when it is really needed and it will download the runtime as expected

**Comment by pvallabhaneni** [comment] 2014-01-24 11:21
This issue is not observed while using VS 2013 plugin [2.0.0016].

**Comment by guarnold** [comment] 2014-01-24 22:03
Could you give us more details, like device/sim OS version, API level used to build the app? 

The next build is on the way. Please verify this issue using the next one.

**Comment by guarnold** [comment] 2014-01-24 23:03
Available in build 2.0.0018 (bundle195).

**Comment by guarnold** [comment] 2014-01-24 23:06
About the first issue, the debugger is not being attached to the running process: Duplicate of #609

About the runtime issue: If the app was build using an API level that is newer than the OS version of the attached device/simulator, an error message is presented to the user stating that he cannot deploy and debug that app. If he wants to use that device/simulator, he have two options: 1 - update the OS version; 2 - select an API level that is compatible with the OS version, rebuild the app and hit play button again.

The runtime window will be presented only when it is really needed and it will download the runtime as expected

**Comment by pvallabhaneni** [comment] 2014-01-25 07:59
Verified the issue using Bundle 195 on fresh machine, now "API levels" dialog is not prompting continuously once API level that supports OS in the device connected downloaded.

But unable to debug the project and "Failed to Launch Debugger" dialog is shown.

**Comment by guarnold** [comment] 2014-01-25 15:59
Please, send more details, like the Win OS, 32 or 64 bits, API level used to build, device or simulator, device/simulator OS version, the application name and the gdb-output log file (check the time this file was updated, just to avoid sending the file related to a previous session, instead of the last attempt).

**Comment by guarnold** [comment] 2014-01-25 20:25
Please, give more details. Before sending the message that the build was good to go, I verified it in VS 2012 Win8 64 bits and VS 2013 WIn7 64 bits machines, using many different combinations of API levels and OS versions from 10.0, 10.1 and 10.2. It worked in all of them, but it is really possible that it is failing for a specific configuration. Send the details so I can do a deep investigation to understand what's causing this issue. For now, I have no idea about how to start the investigation.

**Comment by pvallabhaneni** [comment] 2014-01-27 13:33
I have verified the issue on fresh machine using bundle 195, device OS 10.1.0.4828 on Win 7 32bit  and found as fixed.

**Closed as completed** 2014-01-27 13:46 UTC
Labels: Issue, Completed, P3, VS 2012
