### ISSUE TITLE
[2.0.0016] Debug token window is not refreshing for different device

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#607] opened 2014-01-18 11:25 UTC
Preq: Install VS2012 on Win7 32bit system

Steps to Reproduce:
1. Connect a device that has a debug token installed.
2. Disconnect and reconnect a different device that has a debug token installed.\
3. Open debug token dialog.

Actual Result: Debug token information is not shown on the dialog and "Renew" button is disabled.
![bug](https://f.cloud.github.com/assets/5992422/1946949/1203d4d2-8033-11e3-9975-eca8da6bd6b9.PNG)

Expected Result: Renew button need to enabled and debug token information is refreshed correctly when the "Renew" button is pressed.

**Comment by srinivas4912** [comment] 2014-01-18 13:26
Encounter the same issue in VS2013 plugin from bundle 193[2.0.0016] on Win8.1 with 10.2.1.1925 OS build.

**Comment by guarnold** [comment] 2014-01-20 18:35
This is the expected behavior if the debug token from the second device is different from the one that is associated to the blackberry ID token from your computer (that is stored in the first device). So, you are unable to renew it, but you can add a new debug token in the second device based on the BB ID token that you have on your computer.

Briefly speaking:
1 - if you have a debug token in the device and it was generated from the current BB ID token.csk file stored in your computer, you have only the Renew option available;
2 - if you have a debug token in the device and it was NOT generated from the current BB ID token.csk file stored in your computer, you have only the Add option available;
3 - if you do not have a debug token in the device, you have only the Add option available

**Comment by srinivas4912** [comment] 2014-01-22 08:05
Preq: Install VS2013 plugin from bundle 193[2.0.0016] on Win8.1 using R070 with 10.2.1.1925 build

Steps to Reproduce:
1. Have same debug token installed on both the devices
2. Connect a device that has a debug token installed
3. Invoke debug tokens window
4. Disconnect and reconnect a different device that has a same debug token installed
5. Press Renew

Actual Result: 
On device observed that, Debug token installed but not listed the correct information.
![image](https://f.cloud.github.com/assets/5992406/1971901/84b199d6-833c-11e3-88fe-fd70ceb0ff0d.png)

**Comment by guarnold** [comment] 2014-01-22 16:55
At this moment, you cannot switch devices without reopening the debug token window. That's because:

1 - if you have a debug token in the device and it was generated from the current BB ID token.csk file stored in your computer, you have only the Renew option available;
2 - if you have a debug token in the device and it was NOT generated from the current BB ID token.csk file stored in your computer, you have only the Add option available;
3 - if you do not have a debug token in the device, you have only the Add option available

Those information are gathered when you open the window, so the renew and add buttons will be enabled depending on the device that was attached at the moment you opened the window. 

In your test you are using two devices with exactly the same debug token that were generated by the same bbidtoken.csk file. But the they could have different debug tokens and, in that case, only the Add button should be enabled.

To allow switching devices, we have to implement a new debug token feature, that would be able to recognize when a new device is hooked in the system and update the debug token window.

For now, the workaround is: To switch devices, you have to close the debug token window, switch the device and then reopen the debug token window.

Please, don't close this issue. We will discuss about it later.

**Comment by guarnold** [comment] 2014-01-25 19:55
The last 2 comments, after reopening this issue, is a duplicate of #133

**Comment by dbrgss** [comment] 2014-02-18 16:00
Closing as this is a duplicate

**Comment by dbrgss** [comment] 2014-02-20 12:27
Reopening... closed in error

**Comment by hkopparru** [comment] 2015-01-19 12:09
3.0 plugin UI got changed, where you can upload debug tokens for different devices.
issue is not reproducible
closing this issue now

**Comment by hkopparru** [comment] 2015-01-21 08:07
correcting the earlier comment: we can't upload the same debug token which is created for a particular device(1) to a different device(2). so the same issue is tracking in #133

**Comment by hkopparru** [comment] 2015-01-21 08:08
mistakenly closed this and reopened again.

**Comment by phofman** [comment] 2015-01-21 08:54
Check my comment in #133, if your debug token has multiple PINs inside, you CAN upload it to all devices with matching PINs using the plugin's UI.

**Comment by hkopparru** [comment] 2015-02-10 15:11
as per #133, there is no issue. closing this now.

**Closed as completed by hkopparru** 2015-02-10 15:11 UTC
Labels: Issue, P3, Known Issue (Internal Use Only), VS 2012, VS 2013
