### ISSUE TITLE
[2.0.0022] Able to close Simulator dialog while installing a simulator without any prompt Intermittently.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#640] opened 2014-02-17 12:38 UTC
OS - Win 7 64 bit
Plugin version - 2.0.0022

Steps to Reproduce:
1. Install a simulator.
2. Once simulator is installed status is shown as "complete"
3. Install another simulator.
4. Status is shown as "installing"
5. Click "close" button.

Actual Result: Able to close the simulator dialog immediately without any prompt. Same behavior is observed when an error is occurred during the installation of simulator and if close button is clicked.able to close simulators dialog directly.
Expected Result: "Cancel Installation" prompt need to appear before closing the Simulator dialog.

**Comment by srinivas4912** [comment] 2014-02-21 15:50
Encountered the same issue in Win8.1/OS 10.2.1.1925/VS2013/2.0.0022 on Astro device.
the above same steps followed while installing API levels and Simulators: 
1. we are able to close API levels dialog while installing a API level without any prompt 
2. we are able to close Simulator dialog while installing a simulator without any prompt

Adding VS 2013 label.

**Comment by hkopparru** [comment] 2015-01-19 09:17
latest 3.0 plugin UI got changed. so this problem is not able to reproduce here.we can install and uninstall simulators here

closing this issue now.

**Closed as completed by hkopparru** 2015-01-19 09:17 UTC
Labels: Issue, P3, VS 2012, VS 2013
