### ISSUE TITLE
[2.0.0022] unable to debug on 10.2.1 simulator on vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#665] opened 2014-09-24 18:26 UTC
The app looks to launch but the gdb connection times out.

**Comment by phofman** [comment] 2014-09-24 19:57
Did you tested it against such an old code - tag 2.0.0022? or I just don't understand issues naming convention. If you try PH-v1.7.0 (phofman/vs-plugin@60978dd165e36fb479654ae4a8b4c7a30158693d), what is under review as #664 - all works perfectly.

**Comment by zadmarbella** [comment] 2014-09-24 20:26
Released version 2.0.0022 (build number) of the plugin for VS2012.

**Comment by phofman** [comment] 2014-09-24 20:44
Great, thanks. Just hope it will lead to quicker v3.0 release.

**Comment by dbrgss** [comment] 2015-01-21 13:30
Hanumanth : This needs to be checked against VS2013.. once I can get you unblocked.

**Comment by hkopparru** [comment] 2015-01-21 13:52
tested on VS 2013 with 3.0.0001 plugin, i am facing the same issue which we faced on device (not able to debug) #669

**Comment by hkopparru** [comment] 2015-01-21 13:52
not able to start debug

**Comment by srinivas4912** [comment] 2015-02-02 15:19
Tested on VS2013 with 3.0.0005 plugin on Windows 8.1 and the issue is reproducing.
We observed that the following scenarios:
1. The app is launching on the simulator at the same time the solution is getting closed
2. Unable to hit the break point

**Comment by hkopparru** [comment] 2015-02-11 10:35
tested with [3.0.0015] VS 2013 and the issue is reproducing. where the app is deploying on simulator, then the Visual studio is getting crashed and restarted. screenshot attached.
![debug_simulator](https://cloud.githubusercontent.com/assets/5992379/6145440/d63d7eaa-b207-11e4-9fc9-f6a9071fff2c.JPG)

**Comment by hkopparru** [comment] 2015-02-20 11:31
Verified in [3.0.0017] VS 2013 on both win 7 and Win 8, not able to reproduce this issue. successfully debugging on simulator.

closing this issue.

**Closed as completed by hkopparru** 2015-02-20 11:31 UTC
Labels: Issue, P3
