### ISSUE TITLE
[1.01.0042] simulators dialog list can intermittently after an uninstallation

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#464] opened 2013-09-26 17:45 UTC
preq: have a simulator
1 uninstall that simulator
2 Close right away once Completed
3 Open the Simulator Dialog 

Note: there are instances where the Installed list doesn't update right away and closing and reopening the Simulator dialog causes the recently installed simulator to appear again briefly.

Current Behaviour:
Simulator Window can intermittently vanish

![emptysimulatorlist](https://f.cloud.github.com/assets/1478549/1219929/76b086fa-26d3-11e3-94c2-5d378ca1da50.png)

**Comment by dbrgss** [comment] 2013-11-05 18:19
Estimate: 0.5 days

**Comment by srinivas4912** [comment] 2014-02-17 10:58
This issue is still reproduced using VS2013 plugin from v2.0.0022 on Win8.1, when I followed below steps: 
Once Simulator uninstallation completes click on close and open Get Simulators dialog.
The list of simulators is not shown as in the above screenshot.

Verification failed. Removed "Completed" label and changed the milestone to "Triage".

**Comment by hkopparru** [comment] 2015-01-21 15:47
Verified in [3.0.0001] VS 2013 and the issue is not reproducing
closing this issue.

**Closed as completed by hkopparru** 2015-01-21 15:47 UTC
Labels: Issue, P3
