### ISSUE TITLE
Unable to debug a project on device and simulator

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#552] opened 2013-12-16 16:38 UTC
Preq: Install Visual Studio 2012 on Win7 64 bit system. Install VSNDK plugin

1.Open visual Studio and open a project.
2.Build the project in debug mode.
3.Enter Device ip and password in Blackberry -> settings.
4.Add some breakpoints to the code and Debug the project on the device.
5.Repeat the above steps for the simulator with/without removing the device IP and password in Blackberry->settings.

Actual Result: Error is shown as follows.
"Unable to start debugging. Check your debugger settings by opening project properties and navigating to 'configurtion Properties-> Debugging'

Expected Result: User should be able to debug the project and the control has to hit the breakpoints added to the project.

**Comment by dbrgss** [comment] 2013-12-16 17:52
Question:  Are you trying to debug on a device and simulator at the same time.  In other words.. do you have a device connected via USB and a Simulator open at the same time?

**Comment by hkopparru** [comment] 2013-12-16 19:19
1. For debugging on simulator its showing "No Device IP" dialog but able to debug the code after closing the dialog using OK:
   work around for this issue: close No device ip dialog
2. try with different application for debugging on device.

**Comment by guarnold** [comment] 2013-12-16 19:35
There is an issue, #440, that is related to this "No Device IP" message. It was fixed and the code merged. It was not supposed to happen anymore if you are using the latest build. If it is still reproducible, please reopen issue 440 with more details about how to reproduce it.

However, this issue only prompts the "Missing Device IP" message, but the deploying task works normally in the simulator after closing that window.

**Comment by pvallabhaneni** [comment] 2013-12-17 16:24
I tried deploying and debugging a project on device and simulator on a fresh system. I was able to deploy and debug on the device, but not on to the simulator.

**Comment by guarnold** [comment] 2014-01-13 18:05
Could not reproduce this issue. Could you verify it again using the latest build?

**Comment by pvallabhaneni** [comment] 2014-01-17 10:20
This issue is related to #440 .

**Comment by srinivas4912** [comment] 2014-01-24 15:04
Unable to debug on simulator 10.2.1.1925 using VS2013 plugin from Bundle 193[2.0.0016] on Win8.1

**Comment by guarnold** [comment] 2014-01-24 23:03
Could not reproduce this issue. 

Please verify it again using the latest build 2.0.0018 (bundle195).

**Comment by srinivas4912** [comment] 2014-01-27 13:45
Verified in VS2013 plug-in from bundle 195[2.0.0018] and found as fixed.

**Closed as completed by srinivas4912** 2014-01-27 13:45 UTC
Labels: Issue, P1, Not Reproducible, VS 2013
