### ISSUE TITLE
[2.0.0014] Debugger Does Not Hit Breakpoints

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#589] opened 2014-01-09 16:14 UTC
Preq: 1. Install VS2013 plugin from Bundle 191 on Win8.1 using Trunk build OS
     2. Install The API Level for the device OS(Trunk build)

Steps to Reproduce: 
1.Open visual Studio and open a project.
2.Open bar-descriptor.xml file and set Author information from "set from debug token".
3.Build the project in debug mode.
4.Enter Device ip and password in Blackberry -> settings.
5.Add some breakpoints to the code and Debug the project on the device(DEBUG --> Start Debugging)

Actual Result:
The application was Build and deployed on device with out hitting the debug pointer.

Expected Result:
It should hit the debug pointer while debugging.

**Comment by guarnold** [comment] 2014-01-14 23:32
This issue was fixed and will be available in the next build.

The real issue was #577. 

To help you identify what might be causing the issue, have a look at the gdb-output.log file.

**Comment by guarnold** [comment] 2014-01-14 23:33
Duplicate of #577

**Closed as completed by guarnold** 2014-01-14 23:33 UTC
Labels: Issue, P3, Duplicate, VS 2013
