### ISSUE TITLE
[2.0.0016] Qualifier dropdown is not showing the device IP settings.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#604] opened 2014-01-18 08:06 UTC
Preq: Install VS2012 on Win 7 32bit and VSNDK plugin bundle 193 [2.0.0016]

Steps to reproduce:
1. Enter correct device IP address in blackberry ->Settings.
2. Debug ->attach To Process
3. Open Transport Dropdown and set it to Blackberry
4. Open Qualifier Dropdown

Actual Result: Nothing is shown in the dropdown.
![111](https://f.cloud.github.com/assets/5992422/1946651/5ad00b20-8017-11e3-8758-f8a5cc9f5eb1.png)

Expected Result: Device matches with what was in the Blackberry VS plugin Settings.

**Comment by pvallabhaneni** [comment] 2014-01-18 09:25
Also Available Processes are empty as follows.
![bug](https://f.cloud.github.com/assets/5992422/1946767/648b69e2-8022-11e3-9491-6f4a1654b443.PNG)

**Comment by guarnold** [comment] 2014-01-21 00:11
Workaround:
After entering the BlackBerry settings data, start debugging an app. After debugging an app, the plug-in starts updating the Qualifier from the Attach to Process window, and then you can modify the Device/Simulator IP and that change will be reflected immediately.

This issue is reproducible in 32 and 64 bits environment, for both VS 2012 and 2013.

**Comment by hkopparru** [comment] 2015-02-03 13:14
Tested in [3.0.0005] and the issue is not reproducible, where i am able to see the device details in qualifier drop-down.

closing the issue now.

**Closed as completed by hkopparru** 2015-02-03 13:14 UTC
Labels: Issue, P3, Known Issue (Internal Use Only), VS 2012, VS 2013
