### ISSUE TITLE
[2.0.0018] API Levels are not visible in API Level dialog.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#616] opened 2014-01-25 07:13 UTC
Steps to Reproduce:
1. Install VS2012 on Win7 32bit and Bundle 195 plugin.
2. Go to Blackberry->Settings->GetMore
3.API Level dialog opens.
4. Observe that 10.0 and 10.1 API levels are not visible to install.
![bug](https://f.cloud.github.com/assets/5992422/2001170/33fe2b8e-8590-11e3-8089-ba297d9d2e69.png)

**Comment by guarnold** [comment] 2014-01-25 15:52
I cannot reproduce this issue. Please try toe following steps and send me the details:

Verify if the folders are corrupt. To do that, please check:
1  - the bbndk_vs folder - verify if it contains the target folders for 10.0 and 10.1 (example: target_10_1_0_1020)
2 - the c:\qconfig folder - verify if it contains the xml files for each available target from above item 1;

Second, it can be a communication issue, i.e., the tool used by the update manager might not be able to communicate with the server well. In case it is a communication issue, you can verify it easily by running the eclipsec tool (eclipsec --list-all). You must be able to see a list of all available API levels (ndk). If you cannot get the list, it is a communication issue and you should try again later.

Try to reproduce it more times with the same environment and with different ones (try with VS2013 too, with different machines (32 and 64 bits), and with windows 8 too. If possible, with different combinations). I am asking this because this issue can be related to a specific environment.

**Comment by pvallabhaneni** [comment] 2014-01-28 13:57
This issue is found only once. Verified the same multiple times and this issue is not found again on any of the environments.

**Comment by pvallabhaneni** [comment] 2014-02-03 11:45
This issue is reproducing for the first time of installing the plugin.

Scenario 1:
1.Install VS2012 and VSNDK plugin [2.0.0018] on a fresh machine (Win 7 32/64 bit)
2. Goto Blackberry->Settings->Get More.

Actual Result: Above dialog is shown with no API levels visible in both available list and Installed list.

Scenario 2:
1.Install VS2012 and VSNDK plugin [2.0.0018] on a fresh machine (Win 7 32bit)
2.Open a project.Project opens without any prompt.
3.Build the project. Below dialog is opened and install 10.1 API level.
![bbb](https://f.cloud.github.com/assets/5992422/2064271/6de832c4-8cc8-11e3-8036-2424f4bf08d4.png)
4.Goto Blackberry->Settings->Get More.

Actual Result: Above dialog is shown with no API levels visible in available list and 10.1 is shown in the installed list.

Note: This issue will occur only with fresh machine and for the first time. If API level dialog is closed and opened again from Get More.. list of API levels in available list is shown correctly.

**Comment by hkopparru** [comment] 2015-01-16 12:02
issue is not reproduced with new 3.0 plugin. closing this issue now.

**Closed as completed by hkopparru** 2015-01-16 12:02 UTC
Labels: Issue, P3, VS 2012
