### ISSUE TITLE
[1.01.0033] Closing Update manager selects API level on the top of the list

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#425] opened 2013-09-09 20:31 UTC
preq: have more than 1 api level installed. ie. 10.0.9.2372 and 10.2
1. From Blackberry Setting 
2. Select the item lower in the API level drop down list
3. Click Get More..
4. Close the Update Manager

Current Behaviour:
it will select the top most item. 

Expected Behaviour:
Selected API level is unchanged.

Note: possibility user might not notice this behaviour and continue developing using the wrong API level.

**Comment by dbrgss** [comment] 2013-11-05 18:25
Estimate: 0.5 days

**Comment by hkopparru** [comment] 2015-02-09 10:19
tested with [3.0.0005] VS 2013 and the issue is not reproducible and the UI also changed.

Closing the issue now.

**Closed as completed by hkopparru** 2015-02-09 10:19 UTC
Labels: Issue, P3
