### ISSUE TITLE
[2.0.0018] "Start without Debugging" is prompting for debugger settings

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#630] opened 2014-02-05 10:39 UTC
Pre-requisite: Install VS2012 on Win 7 64 bit or VS 2013 on Win 8.1 System and download 10.2.0.1155 API level.

Steps to Reproduce:
1. Open a project.
2. Goto Debug menu and select "Start without debugging" or press "CTRL + F5".

Actual Result: Following dialog is shown.
![bug](https://f.cloud.github.com/assets/5992422/2086106/9212fea6-8e51-11e3-8165-002a8d1b4afc.png)

but deploy is successful and is shown in output window as "Deploy: 1 succeeded, 0 faild, 0 skipped"

**Comment by guarnold** [comment] 2014-02-07 19:31
Duplicate of #419.

**Closed as completed** 2014-02-13 06:47 UTC
Labels: Issue, P3, Duplicate, VS 2012, VS 2013
