### ISSUE TITLE
[2.0.0022] Update Manager dialog is not shown everytime when close the API Level/Simulator dialogs while downloading is in progress.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#642] opened 2014-02-18 09:30 UTC
Pre-requisite:
System OS: Win 7 / Win 8.1
Plugin version : v2.0.0022
VS version : VS2012 / VS2013

Steps to Reproduce:
1. Install Visual Studio and NDK plugin on a fresh machine.
2. Open Settings dialog and click GetMore.
3. API Level dialog opens and install an API level.
4. Click "Close" while API level is downloading.
5. Cancel Installation dialog appears asking "Are you sure you want to cancel the installation?"
6. Click "Yes"

Actual Result: API level dialog closes and following dialog is shown from Update Manager.
![bug](https://f.cloud.github.com/assets/5992422/2193459/5e612976-987d-11e3-82ec-1c861124c1ff.png)
1. Click GetMore in settings dialog.
2. Click Get Simulators and install a simulator.
3. Click close while installing the simulator.
4.  Cancel Installation dialog appears asking "Are you sure you want to cancel the installation?"
5. Click "Yes"

Actual Result: Above dialog is shown.
1. Repeat the above steps (install either API level or a Simulator) and close while installation is in progress.

Actual Result: Above dialog is not shown intermittently.

Observations: Closing Visual Studio IDE and opening it again and repeating the above steps can reproduce the issue again and again (but intermittently).

**Comment by guarnold** [comment] 2014-02-18 12:32
That dialog must be shown almost every time you cancel the API level/simulator download.

It should not be shown only when the installation is completed successfully. That can happen when you close the window at the final steps of the installation or when you take a long time to click yes, to acknowledge the cancellation. It is possible that the installation was completed, because the download/installation is a different process and does not stop until you click yes. 

Please, verify if the API level/simulator was installed completely when this window is not shown.

**Comment by pvallabhaneni** [comment] 2014-02-18 13:00
Closed the API Level / Simulator dialog immediately after starting the installation. Did not wait until the installation is completed. Still the above dialog is not shown (intermittently).

Assigning back to Triage.

**Comment by hkopparru** [comment] 2015-01-19 09:19
not reproduced in 3.0 plugin.

closing this issue now.

**Closed as completed by hkopparru** 2015-01-19 09:19 UTC
Labels: Issue, P3, VS 2012, VS 2013
