### ISSUE TITLE
[1.01.0022] user is able to spam Debug Token Renew button

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#309] opened 2013-08-21 21:18 UTC
prequisite: have debug token setup
1. From Blackberry > Debug Token
2. Click Renew over and over 

Current Behaviour:
the debug token gets renewed as many times one clicks

**Comment by allee** [comment] 2013-11-05 18:51
est. .5 day

**Comment by guarnold** [comment] 2013-12-19 19:26
Closed because it is a duplicate of issue #111

**Closed as completed by guarnold** 2013-12-19 19:26 UTC
Labels: Issue, P3, Duplicate
