### ISSUE TITLE
Have the Deploy checkbox checked by default (polish)

### ISSUE THREAD

**Issue by allee** [blackberry/VSPlugin#485] opened 2013-10-08 19:04 UTC
This item was never carried forward:

on start up of the first clean install the deploy checkbox is not checked, the default should be that it is checked.

2 participants
dburgess commented a year ago

We dont have much control of this setting. For most of us the setting appears checked by default. We don't know if it's a setting Visual Studio learns to set by default after you click the first time... but it does have some sort of memory.
dburgess commented a year ago

KNOWN ISSUE: We need to make sure we make our users aware that if they try to deploy and it builds with the following message in the output window..
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========
That they need to go into the Configuration Manager... and make sure that the Deploy check box is clicked.

**Comment by PamC** [comment] 2013-10-08 19:06
Release note:
When you attempt to deploy your application the output "Deploy: 0 succeeded, 0 failed, 1 skipped" might appear. Ensure that the Deploy check box is selected in the Configuration Manager.

**Comment by srinivas4912** [comment] 2014-02-06 16:56
The deploy check box is selected/unselected in the Configuration Manager, found the output "Deploy: 1 succeeded, 0 failed, 0 skipped".
Verified using VS2013 plugin from build 2.0.0018 on Win8.1 bit.

**Comment by guarnold** [comment] 2014-02-10 14:55
That polish means that deploy option was not always checked by default. It was not a big issue because it could be checked later, but it would be better to be always checked by default. 

There are two things to verify for this issue:
1 - if the deploy is checked by default;
2 - if the user can check/uncheck the deploy option.

There are three scenarios for verification:

a) open a BlackBerry project and then open the configuration manager. The deploy option might  be checked by default and you must be able to check / uncheck it.

b) create an empty project and open the configuration manager. Then create the  BlackBerry and BlackBerrySimulator configurations. The deploy option might  be checked by default and you must be able to check / uncheck it.

c) create an empty project and import a BlackBerry project. After importing it, open the configuration manager. The deploy option might  be checked by default and you must be able to check / uncheck it.

**Comment by guarnold** [comment] 2014-02-10 14:58
If this issue is not reproducible anymore in VS 2012 and 2013, please remove the Known Issue label before closing it.

**Comment by srinivas4912** [comment] 2014-02-13 07:34
This issue is not reprojducible in VS2012/13 from build 2.0.0022 on Win8.1 and Win7 64 bit.
As per the above comments, three scenarios are verified.

**Closed as completed by srinivas4912** 2014-02-13 07:34 UTC
Labels: Issue, Completed, P3
