### ISSUE TITLE
[3.0.0001] Unable to debug the project in Windows 7 and Windows 8.1 using VS 2013

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#669] opened 2015-01-19 09:59 UTC
Preq: 
System OS: Win 7 64bit and Windows 8.1
VS version : VS2013
API level : 10.3.1.995

Steps to Reproduce:
1. Open "FallingBlocks_PB_MT_001" project and build the project.
2. Open a source file and add a break-point.
3. Click "F5" or select "Debug -> Start Debugging"

Actual Result: Error message is shown as "Unable to start program"

![debugging issue](https://cloud.githubusercontent.com/assets/5992422/5798671/b6e0695c-9fef-11e4-9e50-ff6dfdb44399.png)

Note: When "deploy" option is selected by right clicking on the project, application is being deployed onto the device.

**Comment by phofman** [comment] 2015-01-19 11:40
Could you please check it against the 3.3.1 version from my [fork](/phofman/vs-plugin/wiki)? It can be downloaded from [here](https://visualstudiogallery.msdn.microsoft.com/9a03ae7e-b786-41a7-a63b-dc0d9fe818d2).

**Comment by pvallabhaneni** [comment] 2015-01-19 12:09
Issue is still reproducing after installing 3.3.1 version also.

**Comment by phofman** [comment] 2015-01-19 12:22
I am not able to reproduce it. I took the FallingBlocks from samples folder and I able to place a breakpoint, stop the app etc.

![fallingblocks_debugging](https://cloud.githubusercontent.com/assets/475630/5800336/8068214c-9fdd-11e4-8409-c16a43830dcf.png)

Sometimes instead of a valid code place debugger stops with a 'frame not found' window, but usually navigating from 'Threads' window works. Although this will be fixed, when GDB integration is rewritten ;)

Could you provide more info about your build? Please attach logs from Output Window (_BlackBerry_ pane as on attached image) so I could investigate more. Do you see any warnings in Error-List Window?

**Comment by dbrgss** [comment] 2015-01-20 14:19
So the sample applications that we are using were converted using the older tooling.  Therefore they have old project configurations for BlackBerry and BlackBerry Simulator.   I was wondering if these old settings might be having an adverse affect on the build.   When you do your testing do you remove these configurations and allow your code to re-add them?

**Comment by hkopparru** [comment] 2015-01-20 14:56
in configuration manager where i am able to delete and add BlackBerry platform successfully(many times tested)

But once I delete the BlackBerry Simulator platform then i am not able to add it again.

please see the below screenshots for before and after deletion of BlackBerry Simulator platform.

![image](https://cloud.githubusercontent.com/assets/5992379/5819281/8e73fa58-a0e2-11e4-838f-9e985cbeb571.png)

![image](https://cloud.githubusercontent.com/assets/5992379/5819289/a2a52d26-a0e2-11e4-9026-5c954be9e855.png)

**Comment by phofman** [comment] 2015-01-20 15:02
It's correct. There isn't anymore 'BlackBerrySimulator' platform, so you can't add it again. The first time it was just an item read by VS2013 from data from project settings.

To build and deploy for a simulator you need to change the CPU Type as explained in #670.

**Comment by dbrgss** [comment] 2015-01-20 15:59
When I try to debug the HelloWorldDisplay application in VS2013 on a 10.3.1 device its getting through the entire build process but then it hits a dialog 

![image](https://cloud.githubusercontent.com/assets/793427/5820507/46060ecc-a093-11e4-9f9d-0c46f70c2212.png)

Pawell.. can you advise what the process should be from here.   If I pick the HelloWorldDisplay project.. then the Path box is disabled..  and if I try to click OK.. it says I wont be able debug..

Thanks

**Comment by phofman** [comment] 2015-01-20 16:14
This is my UI :)
When you start debugging, path to local binary must be passed to GDB. The plugin reads this value from project settings or tries to guess typical location for Cascades apps. But if the output-file can't be found (as the build is actually performed by makefile), it will ask developer to specify it (look for IAttachDiscoveryService implementation).

Your screen-shot shows you haven't set one in project settings (or reading has a bug). From the project list, you must select the last option in that case to be able to specify path manually. If it's left empty, nothing will be passed to GDB and setting breakpoints won't be supported AFAIK.

Could you also try it against v3.3.1?

**Comment by dbrgss** [comment] 2015-01-20 17:40
So from my trace.  It appears that in the ProjectHelper class.. 

GetValue() Function:

```
        var activeConfiguration = project.ConfigurationManager.ActiveConfiguration;
        var currentConfigurationName = activeConfiguration.ConfigurationName;
        var currentPlatformName = activeConfiguration.PlatformName;
        var cppProject = project.Object as VCProject;

        if (cppProject != null)
```

The casting of the project.Object as a VCProject is returning NULL which is why output file is coming back as blank.  

Continuing to investigate why its null.. as when I trace and inspect the node it appears to be instantiated.

**Comment by phofman** [comment] 2015-01-20 18:30
Are you sure the GdbHost.exe is correctly installed (ConfigDefaults.GdbHostPath expects it to be next to the package dll file, what is not done automatically)? It's fixed by commit @e4cf4da983e58ecade54123a27acf874ba53d10d, which is an ultimate fix for debugging. It is just the next one above the top of the master repo's HEAD.

I still don't think that testing and releasing a 3-months old code is a good idea, even if Russell is gone for now ;)

**Comment by dbrgss** [comment] 2015-01-26 15:14
Hi Pawel.   I have been given the go ahead to pull in your latest code if you are still willing to post it.  Please let me know if you have any issues with this.. :-)

Dave

**Comment by phofman** [comment] 2015-01-26 17:03
I already made it available to you, just after last call with Russell ;) Take a look at pull-request #667. Probably the title is a bit misleading.

Personally I have no problems with sharing it. This is the most stable code and wish to make it a base version for everybody (ok - GDB is a bit 'strange' and sometimes doesn't correctly navigate to source-code, but doesn't crash at the same time :D). I also use this version for my own apps development.

Just remember I did published it, so all links and docs point to my forked repo instead of the master one of BlackBerry. Lou was supposed to provide some plan, how we want to handle my contribution and fairly mention my name, but he didn't contact me yet/still... so till that please leave those links as they are.

One info - if you want to have QML colorizer working, you might need to delete this registry key: `HKCU\Software\Microsoft\VisualStudio\<version>\FontAndColors\Cache` otherwise IDE will ignore all colors set by plugin.

Happy testing ;) Let me know, if you need anything more.

**Comment by hkopparru** [comment] 2015-01-30 13:56
Good news here, tested on [3.0.0005] and now i am able to debug the projects on windows 7 environment and needs to test on windows 8.

**Comment by hkopparru** [comment] 2015-02-02 11:27
also we are able to debug on windows 8 with [3.0.0005]

**Comment by hkopparru** [comment] 2015-02-02 15:01
closing this issue now.

**Closed as completed by hkopparru** 2015-02-02 15:01 UTC
Labels: Issue, VS 2013
