### ISSUE TITLE
[2.0.0018] Selected API level is modifying when "API Level" dialog is opened & Closed.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#628] opened 2014-02-04 07:39 UTC
Pre-requisite: 
System OS: Win 7 32bit / 64bit
Plugin Version : 2.0.0018

Steps to Reproduce:
1. Install more than 1 API level.
2. Select the 2nd or 3rd API level in the API level dropdown present in Settings dialog
3. Select "Get More.." button
4. Close "API Level" dialog,

Actual Result: API level in the dropdown control is changing to the 1st API level by order.

Expected Result: API level selected in the dropdown need to persist before or after closing "API Level" dialog.

**Comment by guarnold** [comment] 2014-02-07 20:19
Duplicate of issue #425.

**Closed as completed** 2014-02-12 11:23 UTC
Labels: Issue, P3, Duplicate, VS 2012
